version: '3.0'

services:
  server:
    build: ./readium-client
    ports:
      - "80:80"
  readium-api:
    build:
      context: ./readium-api
      args:
        - NODE_ENV=production
        - PORT=5000
    command: bash -c "rm -rf /usr/local/app/node_modules/* &&  pm2-runtime index.js"
    env_file:
      - ./secret.env
    environment:
      - MONGO_USERNAME=readium-oniichan
      - MONGO_PASSWORD=11410197100105117109451111101051059910497110
      - MONGO_HOSTNAME=readium-db
      - MONGO_DATABASE_NAME=readium
      - MONGO_PORT=27017    
      - CLIENT_URL=http://localhost
      - SERVER_URL=http://localhost/api
    volumes:
      - exclude:/usr/local/app/node_modules/
    depends_on:
      - readium-db
      - readium-rabbit
      - elasticsearch
  
  readium-db:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=readium-oniichan
    - MONGO_INITDB_ROOT_PASSWORD=11410197100105117109451111101051059910497110
    - MONGO_INITDB_DATABASE=readium

  readium-rabbit:
    image: rabbitmq:3.9.9

  readium-ai-service:
    build:
      context: ./readium-ai-service
      args:
        - PORT=4000
    environment:
      - MONGO_USERNAME=readium-oniichan
      - MONGO_PASSWORD=11410197100105117109451111101051059910497110
      - MONGO_HOSTNAME=readium-db
      - MONGO_DATABASE_NAME=readium
      - MONGO_PORT=27017

  elasticsearch:
    image: elasticsearch:7.14.2
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    depends_on:
      - readium-rabbit

volumes:
  exclude:
  elasticsearch: